Inspinia_MVC5/Controllers/electestController.cs
using stay_calm_db_tests;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Inspinia_MVC5.Controllers
{
    public class electestController : Controller
    {
        private userContext db = new userContext();

        public ActionResult user_current()
        {
            return View(db.USERS.ToList());
        }

        public ActionResult view_ioalarm_type(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            // Me viewing all HG Status that is connected to site 
            var hg_attached = (from d in db.io_alarms
                               where d.siteuser.Id == id
                               select d).ToList();

            if (hg_attached == null)
            {
                return HttpNotFound();
            }




            // Send this also to view 
            ViewBag.idforlinkinglimit = id;

            return View(hg_attached);
        }

        public ActionResult view_sites()
        {
            return View(db.siteuser.ToList());
        }




    }
}

Inspinia_MVC5/Controllers/sv01Controller.cs
using SendGrid;
using stay_calm_db_comms;
using stay_calm_db_tests;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;



namespace elementalelec.controller
{
    public class sv01Controller : Controller
    {
        
        public async Task<ActionResult> get(String mserial, String mversion, String chparam, String oldsddata, String trantype, String transubtype, String hgparam, String hgstatus, String idvalues, String mdnt)
        {
            // EFConfiguration.SuspendExecutionStrategy = true;

            if (chparam != null)
            {
                userContext test = new userContext();
                var chserial = test.chparamdbs.Where(x => x.sitetoboards.serialboard == mserial).FirstOrDefault();


                if (chserial != null)
                {
                    String xparams_str = chserial.xparams.ToString();
                    String yparams_str = chserial.yparams.ToString();

                    String zparams_str = chserial.zparams.ToString();
                    String aparams_str = chserial.aparams.ToString();

                    ViewBag.is_found = "EEstatus=" + 1;
                    ViewBag.chparms = "," + xparams_str + "," + yparams_str + "," + zparams_str + "," + aparams_str + ",";
                }
                else
                {
                    ViewBag.is_found = "EEstatus=0";
                    return View();
                }



                return View();
            }

            try
                {
                String utc = DateTime.UtcNow.ToString("yyyy,MM,dd,HH,mm,ss", CultureInfo.InvariantCulture);

                string newmversion = "";
                    int character = 0;

                    foreach (char c in mversion)
                    {


                        if (character == 1)
                        {

                            newmversion = newmversion + "0";

                        }

                        else
                        {
                            newmversion = newmversion + c;
                        }

                        character = character + 1;
                    }

                    

                    //   String url = "ttp://elementalelec.azurewebsites.net/relax/load?ph=0&ch=" + idvalues_id + "&temp=" + idvalues_value + "&dateplot=" + dateformat + "&serialsite=" + mserial;
                    // ttp://elementalelec.azurewebsites.net/sv01/get?mserial=530173&mversion=10413&trantype=HG&transubtype=status&hgstatus=0,0,0,0,0,0,0,68,69,1,0,0,40&mdnt=2014,5,5,1,59,53

                    String url = "";

                    if (hgparam != null)
                    {
                        if (oldsddata != null)
                        {
                        
                            url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion
                           + "&oldsddata=" + oldsddata + "&trantype=" + trantype
                           + "&transubtype=" + transubtype + "&hgparam=" + hgparam + "&mdnt=" + utc;

                        }

                        else
                        {
                            url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion + "&trantype=" + trantype
                            + "&transubtype=" + transubtype + "&hgparam=" + hgparam + "&mdnt=" + utc;
                        }
                    }
                    else
                    {
                        if (idvalues != null && trantype == "AC")
                        {
                        // Must be able to store 255,255 rather than 255,0
                        //ttp://elementalelec.azurewebsites.net/sv01/get?mserial=0890CA&mversion=10414&trantype=AC&idvalues=255
                        //ttp://svr01.cpsys.com.au/receiver.php?mserial=0890CA&mversion=10414&trantype=AC&idvalues=255,0

                        // edited IO ALARM value for 255,0
                        string edit_idvalues = null;

                        // Checking each character for errors
                        foreach (char c in idvalues)
                            {
                                if (c < '0' || c > '9')
                                {
                                    if (c == ',')
                                    {
                                        // Changing the ID values to 255,0 and 255,255 to 255,0
                                        string[] chan = idvalues.Split(',');
                                        edit_idvalues = chan[0] + ",0";

                                    }
                                    else
                                    {
                                        ViewBag.is_found = 0;
                                        return View();
                                    }
                                }

                            }

                            if (edit_idvalues == null)
                            {
                                edit_idvalues = idvalues + ",0";
                            }

                        //  idvalues = idvalues + ",0";
                        url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion + "&trantype=" + trantype
                                 + "&idvalues=" + edit_idvalues + "&mdnt=" + utc; 

                        }

                        else if (hgstatus != null)
                        {
                            url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion + "&trantype=" + trantype
                            + "&transubtype=" + transubtype + "&hgstatus=" + hgstatus + "&mdnt=" + utc;

                        }

                        else if (idvalues != null && trantype != "AC")
                        {
                            string str_re_do = "";
                            string addition = "";
                            string break_idval = idvalues;

                            string four_one = "";
                            string four_zero = "";

                            var primeArray = break_idval.Split(',');

                            for (int i = 0; i < primeArray.Length; i++)
                            {

                                string idvalues_id = break_idval.Split(',')[i];
                                string idvalues_value = break_idval.Split(',')[i + 1];

                             if(idvalues_id == "140")
                             {
                                double multi;
                                double.TryParse(idvalues_value, out multi);

                                  // If the serial number DOES NOT EQUAL "B46567" 
                                   if (mserial == "B46567")
                                   {
                                      // Do nothing 
                                   }
                                    
                                   else if(mserial == "0890CA")
                                    {
                                      // Do nothing 
                                    }
    
                                     else {

                                        multi = multi / 10;

                                        idvalues_value = multi.ToString("0.##");
                                    }

                                     four_zero = idvalues_value;

                                 }

                         
                               else if (idvalues_id == "141")
                                {
                                   double multi;
                                   double.TryParse(idvalues_value, out multi);

                                    multi = multi * 10;

                                    idvalues_value = multi.ToString("0.##");

                                    four_one = idvalues_value;
                                }
                                else
                                {
                                    addition = idvalues_id + "," + idvalues_value + ",";
                                    str_re_do = addition + str_re_do;
                                }


                                i = i + 1;
                            }


                            // 141 = conductivity ms/cm    140 = UV
                            str_re_do = str_re_do + "140," + four_one + "," + "141," + four_zero;

                            if (oldsddata != null)
                            {

                                //String utc = DateTime.UtcNow.ToString("yyyy,MM,dd,HH,mm,ss", CultureInfo.InvariantCulture);

                                url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion
                                       + "&oldsddata=" + oldsddata + "&trantype=" + trantype
                                       + "&transubtype=" + transubtype + "&idvalues=" + str_re_do + "&mdnt=" + utc;
                            }
                            else
                            {
                                url = "http://svr01.cpsys.com.au/receiver.php?mserial=" + mserial + "&mversion=" + newmversion + "&trantype=" + trantype
                                 + "&transubtype=" + transubtype + "&idvalues=" + str_re_do + "&mdnt=" + utc;
                            }
                        }


                    }


                   //"Fire and forget" is only an acceptable approach if you don't care whether http actually completes.
                    HttpWebRequest myRequest = (HttpWebRequest)WebRequest.Create(url);
                   // myRequest.Method = "POST";

Inspinia_MVC5/Views/electest/user_current.cshtml
@model  IEnumerable<stay_calm_db_tests.newusers>



<head>
    <style>
        .table {
            margin-left: 100px;
            margin-top: 50px;
        }

        #details {
            padding-left: 50px;
            
        }
        .view_sites{
            margin-left: 100px;
            margin-top: 30px;
        }

        .view_serial{
            margin-left: 100px;
            margin-top: 10px;
            float:left;
        }
    </style>
</head>

<h2 id="details">All Normal User Accounts</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Username </th>
            <th>Password </th>
            <th>Email </th>
            <th>Edit </th>
            <th>Delete User </th>
            <th>Sites</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelitem => item.username)</td>
                <td>@Html.DisplayFor(modelitem => item.password)</td>
                <td>@Html.DisplayFor(modelitem => item.email)</td>
                <td>@Html.ActionLink("Edit", "edit_normal_user", new { ID = item.ID })</td>
                <td>@Html.ActionLink("Delete", "delete_normal_user", new { ID = item.ID })</td>
                <td>@Html.ActionLink("Site attached", "error_site_display", new { ID = item.ID })</td>
               
            </tr>
         }
    </tbody>
</table>

<div class="view_sites">
    <h2>All Sites</h2>
    <p>@Html.ActionLink("View Sites", "view_sites")</p>
</div>

<div class="view_serial">
    <h2>All Serial Boards</h2>
    <p>@Html.ActionLink("View boards", "view_serial")</p>
</div>

Inspinia_MVC5/Views/electest/view_ioalarm_type.cshtml
@model  IEnumerable<stay_calm_db_tests.io_alarms>

@using System.Linq

<head>
    <style>
        .table {
            margin-left: 40px;
        }

        #details {
            padding-left: 50px;
        }

        #title {
            padding-left: 60px;
        }

        #title_username p {
            float: left;
            padding-left: 40px;
            padding-top: 30px;
            padding-bottom: 20px;
            font-weight: bold;
        }

        #nomodel {
            float: left;
            padding-left: 50px;
            padding-top: 20px;
            padding-bottom: 30px;
        }

        #adding_more_sites p {
            padding-top: 50px;
            padding-left: 40px;
            padding-bottom: 20px;
            float: left;
        }

        .back_btn_design {
            float: left;
            margin-left: 90px;
            background-color: #5DFC0A;
            width: 100px !important;
            height: 30px !important;
            font-size: 14px;
            text-align: center;
            border: 1px solid #357ebd;
            color: #000000;
            padding-top: 4px;
        }

            .back_btn_design:hover {
                color: #000000;
            }
    </style>
</head>


<h2 id="details">Sites Currently attached to User</h2>

<div id="title_username">

    @foreach (var item in Model.Take(1))
    {
        <p>Username:        @Html.DisplayFor(modelitem => item.siteuser.user_site) </p>
        <p>Password:        @Html.DisplayFor(modelitem => item.siteuser.sitetoboards.serialboard) </p>
        <p>ID:              @Html.DisplayFor(modelitem => item.siteuser.Id)</p>
    }
</div>


<!--https://code.msdn.microsoft.com/ASPNET-MVC-Application-b01a9fe8/sourcecode?fileId=134759&pathId=1349546619-->

@if (!Model.Any())
{
    <div id="nomodel">
        <p>
            No HG status are attached to this User
            <br />Please contact Add limits by going back
        </p>
    </div>

}
else
{

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Site Name</th>
                <th>Terminal Serial </th>
                <th>Site  id</th>
                <th>Switch Number</th>
                <th>Alarm Name</th>
                <th>Edit Alert Type</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelitem => item.siteuser.user_site)</td>
                    <td>@Html.DisplayFor(modelitem => item.siteuser.sitetoboards.serialboard)</td>
                    <td>@Html.DisplayFor(modelitem => item.siteuser.Id)</td>
                    <td>@Html.DisplayFor(modelitem => item.switch_number)</td>
                    <td>@Html.DisplayFor(modelitem => item.alarm_name)</td>
                    <td>@Html.ActionLink("Edit Alert Type", "edit_alarms", new { ID = item.Id })</td>
                    <td>@Html.ActionLink("Delete", "delete_io_alarms", new { ID = item.Id })</td>
               </tr>
            }
        </tbody>
    </table>
}

<div id="adding_more_sites">

    <a>@Html.ActionLink("Add Alarms", "add_alarms", new { id = @ViewBag.idforlinkinglimit })</a>
    <a>@Html.ActionLink("Go Back", "view_sites", "sv01", new { @class = "back_btn_design" })</a>

</div>

Inspinia_MVC5/Views/electest/view_sites.cshtml
@model  IEnumerable<stay_calm_db_tests.siteuser>

<head>
    <style>
        .table {
            margin-left: 100px;
            margin-top: 50px;
        }

        #details {
            padding-left: 50px;
        }

        .view_sites {
            margin-left: 100px;
            margin-top: 30px;
        }

           .back_btn_design{
            float:left;
          margin-left: 90px;
         background-color: #5DFC0A;
         width: 100px !important;
         height: 30px !important;
         font-size: 14px;
         text-align: center;
         border: 1px solid #357ebd;
         color: #000000;
         padding-top: 4px;
      }

      .back_btn_design:hover{
         color: #000000;
       }
    </style>
</head>

<h2 id="details">Site List</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Site </th>
            <th>GMT</th>
            <th>Serial </th>
            <th>Edit </th>
            <th>Data Types </th>
            <th>HG Status</th>
            <th>I/O Alarm </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelitem => item.user_site)</td>
                <td>@Html.DisplayFor(modelitem => item.sitetoboards.serialboard)</td>
                <td>@Html.DisplayFor(modelitem => item.GMT)</td>

                @if (item.serial_board_id.Equals(0))
                {
                <td>@Html.ActionLink("No serial attached ! Please click here to Attach a Serial", "attach_a_serial", new { ID = item.Id })</td>
                <td>@Html.ActionLink("Delete Site", "dele_site", new { ID = item.Id })</td>
                }
                else {
                <td>@Html.ActionLink("Edit site", "edit_sites", new { ID = item.Id })</td>
                <td>@Html.ActionLink("View Data Types", "edit_graph_limit", new { ID = item.Id })</td>
                <td>@Html.ActionLink("View HG status", "view_hg_status", new { ID = item.Id })</td> 
                <td>@Html.ActionLink("View I/O Type", "view_ioalarm_type", new { ID = item.Id })</td> 
                }
             </tr>
        }
    </tbody>
  </table>


<a>@Html.ActionLink("Go Back", "user_current", "sv01", new { @class = "back_btn_design" })</a> 