Inspinia_MVC5/Controllers/siteaccountController.cs
using newtest.Models.sitelistmodel;
using stay_calm_db_tests;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspinia_MVC5.Controllers
{
    public class siteaccountController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        private userContext db = new userContext();

    public ActionResult site_list()
    {
      sitelist_model sitelistModel = new sitelist_model();
      sitelistModel.serialnumber = new List<string>();
      sitelistModel.serialid = new List<string>();
      sitelistModel.sites = new List<string>();
      sitelistModel.site_id = new List<string>();

            var taken = (from x in db.siteuser
                         select x.sitetoboards.Id).ToList();

            var list = (from x in db.sitetoboards
                        where !taken.Contains(x.Id)
                        select new {
                            x.serialboard,
                            x.Id
                        }).ToList();
            
      if (list.Count() == 0)
      {
        sitelistModel.serialnumber.Add("No Avaliable Serials Please add more");
        sitelistModel.serialid.Add("");
      }
      else
      {
        foreach (var data in list)
        {
          sitelistModel.serialnumber.Add(data.serialboard);
          sitelistModel.serialid.Add(data.Id.ToString());
        }
      }



            var siteuser = (from x in db.siteuser
                            select new {
                                x.user_site,
                                x.Id
                            }).ToList();
     
      foreach (var data in siteuser)
      {
        sitelistModel.sites.Add(data.user_site);
        sitelistModel.site_id.Add(data.Id.ToString());
      }
      return View(sitelistModel);
    }

        public PartialViewResult user(string username, string password, string[] options)
        {
            usermodellist usermodellist = new usermodellist();
            usermodellist.username = new List<string>();
            usermodellist.password = new List<string>();
            usermodellist.email = new List<string>();


            if(username !=null)
            {

                newusers add_user = new newusers();
                add_user.username = username;
                add_user.password = password;
                db.USERS.Add(add_user);
                db.SaveChanges();

                if (options != null)
                {
                    int num = db.USERS.Where(x => x.username == username).Select(x => x.ID).FirstOrDefault();
                    int result = 0;
                    for (int index = 0; index < options.Length; ++index)
                    {
                        int.TryParse(options[index], out result);
                        db.site_user_link.Add(new site_user_link()
                        {
                            siteuserId = result,
                            newusersID = num
                        });
                        db.SaveChanges();
                    }
                }
            }


            var users = (from x in db.USERS
                         select x).ToList();

            foreach (newusers newusers in users)
            {
                usermodellist.username.Add(newusers.username);
                usermodellist.password.Add(newusers.password);
                usermodellist.email.Add(newusers.email);
            }
            return PartialView(usermodellist);
        }


        public PartialViewResult serial(string serial)
        {
            serialmodellist serialmodellist = new serialmodellist();
            serialmodellist.serialnumber = new List<string>();
            serialmodellist.is_attached = new List<string>();
            serialmodellist.site = new List<string>();
            serialmodellist.site_id = new List<string>();

            if (serial != null)
            {
                serial.Replace(" ", string.Empty);
                var newboardid = (from x in db.sitetoboards
                                  where x.serialboard == serial
                                  select x.serialboard).FirstOrDefault();

                if(newboardid != serial)
                {
                    String date_format = DateTime.UtcNow.ToString("MM/dd/yyyy HH:mm:ss", CultureInfo.InvariantCulture);


                    DateTime date;
                    // Check if date is valid 
                    DateTime.TryParse(date_format, out date);

                    serial.Replace(" ", string.Empty);

                    sitetoboards newboards = new sitetoboards();
                    newboards.serialboard = serial;
                    newboards.lastseen = date;
                    db.sitetoboards.Add(newboards);
                    db.SaveChanges();


                    var site_id = (from x in db.sitetoboards
                                      where x.serialboard == serial
                                      select x.Id).FirstOrDefault();

                    response_comms add_response = new response_comms();
                    add_response.response_bit = 1;
                    add_response.frequency = 10;
                    add_response.once_on_server = 1.1;
                    add_response.comms_board_id = site_id;

                    db.response_comms.Add(add_response);
                    db.SaveChanges();

                    chparamdbs add_new_chparams = new chparamdbs();
                    add_new_chparams.xparams = 0;
                    add_new_chparams.yparams = 0;
                    add_new_chparams.zparams = 0;
                    add_new_chparams.aparams = 0;
                    add_new_chparams.serial_to_chparams = site_id;
                    db.chparamdbs.Add(add_new_chparams);
                    db.SaveChanges();
                }
                else
                {
                    
                }
                
            }
            else
            {
                serial = "0";
            }

           

            var sitetoboards1 = (from x in db.sitetoboards
                                 select new
                                 {
                                     x.serialboard,
                                     x.Id
                                 }).ToList();

            var all_site_serials = (from x in db.siteuser
                                    select new
                                    {   x.user_site,
                                        x.serial_board_id
                                    }).ToList();
            
            foreach (var item in sitetoboards1)
            {
                serialmodellist.serialnumber.Add(item.serialboard);
                serialmodellist.site_id.Add(item.Id.ToString());

                if (item.serialboard == serial)
                {
                    serialmodellist.is_attached.Add("No");
                    serialmodellist.site.Add("None");
                }
                else
                {
                    
                    if (all_site_serials.Where(x=> x.serial_board_id == item.Id).FirstOrDefault() == null)
                    {
                        serialmodellist.is_attached.Add("No");
                        serialmodellist.site.Add("None");
                    }
                    else
                    {
                        serialmodellist.is_attached.Add("Attached");
                        serialmodellist.site.Add(all_site_serials.Where(x => x.serial_board_id == item.Id).Select(x => x.user_site).FirstOrDefault());
                    }
                    

                }
            }
            return PartialView(serialmodellist);
        }


        public PartialViewResult site(string serial, string sitename, string tmzone)
        {
            sitemodellist sitemodellist = new sitemodellist();
            sitemodellist.status = new List<string>();
            sitemodellist.date_lastseen = new List<string>();
            sitemodellist.sites = new List<string>();
            sitemodellist.timezone = new List<string>();
            sitemodellist.serialnumber = new List<string>();
            sitemodellist.hgstatus_count = new List<string>();
            sitemodellist.ioalarms_count = new List<string>();
            sitemodellist.graph_data_count = new List<string>();

            if (sitename != null && serial != null)
            {

                sitename.Replace(" ", string.Empty);
                int result = 0;
                int.TryParse(serial, out result);
                

                siteuser attaching = new siteuser();
                attaching.user_site = sitename;
                attaching.serial_board_id = result;
                attaching.GMT = tmzone;
                db.siteuser.Add(attaching);
                db.SaveChanges();

                // Adding the IO Alarms
                var id_limits = (from y in db.siteuser
                                 where y.user_site == sitename && y.serial_board_id == result
                                 select y.Id).FirstOrDefault();

                // IO Alarms 
                io_alarms naming_alarms = new io_alarms();
                naming_alarms.switch_number = 1;
                naming_alarms.alarm_name = "sw1";
                naming_alarms.site_id_link = id_limits;
                db.io_alarms.Add(naming_alarms);
                db.SaveChanges();


                // Graph Data types + Limits 
                graph_limit site_to_twenty_two = new graph_limit();

                site_to_twenty_two.graph_data_type_id = 5;
                site_to_twenty_two.site_id_to_limit = id_limits;  // 16
                site_to_twenty_two.lower_limit_to = 0;
                site_to_twenty_two.lower_limit_from = 0;
                site_to_twenty_two.upper_limit_to = 0;

Inspinia_MVC5/Views/siteaccount/edit_page.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{
    ViewBag.Title = "Edit Serial";
}


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit Terminal Serial</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboards", "Dashboards")">Home</a>
            </li>
            <li class="active">
                <strong>Terminal edit</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <form id="form">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-1"> Serial info</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">

                                <div class="table-responsive">
                                    <table class="table table-stripped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Serial Number
                                                </th>
                                                <th>
                                                    Actions
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <input type="text" class="form-control" name="editserial" value="@ViewBag.serial"/>
                                                    <input type="hidden" name="id" value="@ViewBag.id_serial">
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("edit_page","siteaccount",new {delete_id =ViewBag.id_serial})" type="button" class="btn btn-white deletebtn"><i class="fa fa-trash"></i></a> 
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                                <a href="@Url.Action("edit_page","siteaccount",new {back_id = "1"})" type="button" class="btn btn-warning btn-lg backbtn">Back</a> 
                                <button type="submit" class="btn btn-warning btn-lg savebtn" style="float:right;">Save Changes</button>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")


<script type="text/javascript">
        $(document).ready(function () {

         

            //$('.backbtn').click(function () {
            //    swal({
            //        title: "Are you sure?",
            //        text: "any changes WILL NOT take effect",
            //        type: "warning",
            //        showCancelButton: true,
            //        confirmButtonColor: "#DD6B55",
            //        confirmButtonText: "Yes, I want to go back!",
            //        closeOnConfirm: false
            //    }, function () {
                   


            //    });
            //});

            $('#form').on('submit', function (e) {
           
                $('.savebtn').show(function () {
                    swal({
                        title: "Saving....",
                        text: "Please wait !",
                    });
                });

                $.ajax({
                    url: "edit_page",
                    type: "POST",
                    data: $(this).serialize(),
                    success: function () {
                        $('.savebtn').show(function () {
                            swal({
                                title: "Saved!",
                                text: "You will be Re-Directed Soon!",
                                type: "success"
                            });
                        });
                    },
                    error: function (jXHR, textStatus, errorThrown) {
                        alert("Error has occured, Please check your internet or Browser !");
                    }
                });
            });


        });
</script>


}

Inspinia_MVC5/Views/siteaccount/edit_users.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@{
    ViewBag.Title = "Edit Users";
}



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit Terminal Serial</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboards", "Dashboards")">Home</a>
            </li>
            <li class="active">
                <strong>User edit</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <form id="form">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-1"> User info</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">

                                    <table class="table table-stripped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>
                                                   Username
                                                </th>
                                                <th>
                                                   Password
                                                </th>
                                                <th>
                                                    Email
                                                </th>
                                                <th>
                                                    Sites
                                                </th>
                                                <th>
                                                    Delete
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <input type="text" class="form-control" name="editserial" value="@ViewBag.serial" />
                                                    <input type="hidden" name="id" value="@ViewBag.id_serial">
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control" name="editserial" value="@ViewBag.serial" />
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control" name="editserial" value="@ViewBag.serial" />
                                                </td>
                                                 <td>
                                                     <select id="selectuser" data-placeholder="Choose a Serial..." class="chosen-select form-control" multiple name="options">
                                                             <option value="1">Test option</option>
                                                             <option value="1">Test option</option>
                                                             <option value="1">Test option</option>
                                                     </select>
                                                 </td>
                                                <td>
                                                    <a href="@Url.Action("edit_page","siteaccount",new {delete_id =ViewBag.id_serial})" type="button" class="btn btn-white deletebtn"><i class="fa fa-trash"></i></a>
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                <a href="@Url.Action("edit_page","siteaccount",new {back_id = "1"})" type="button" class="btn btn-warning btn-lg backbtn">Back</a>
                                <button type="submit" class="btn btn-warning btn-lg savebtn" style="float:right;">Save Changes</button>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </form>
</div>

@section Styles {
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/chosen")

    <script type="text/javascript">
        $(document).ready(function () {



          

            $('#form').on('submit', function (e) {

                $('.savebtn').show(function () {
                    swal({
                        title: "Saving....",
                        text: "Please wait !",
                    });
                });

                $.ajax({
                    url: "edit_page",
                    type: "POST",
                    data: $(this).serialize(),
                    success: function () {
                        $('.savebtn').show(function () {
                            swal({
                                title: "Saved!",
                                text: "You will be Re-Directed Soon!",
                                type: "success"
                            });
                        });
                    },
                    error: function (jXHR, textStatus, errorThrown) {
                        alert("Error has occured, Please check your internet or Browser !");
                    }
                });
            });




            var config = {
                '.chosen-select': {},
                '.chosen-select-deselect': { allow_single_deselect: true },
                '.chosen-select-no-single': { disable_search_threshold: 10 },
                '.chosen-select-no-results': { no_results_text: 'Oops, nothing found!' },
                '.chosen-select-width': { width: "95%" }
            }
            for (var selector in config) {
                $(selector).chosen(config[selector]);
            }


        });
    </script>


}

Inspinia_MVC5/Views/siteaccount/serial.cshtml
@model newtest.Models.sitelistmodel.serialmodellist

<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Serial list</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="#">Config option 1</a>
                    </li>
                    <li>
                        <a href="#">Config option 2</a>
                    </li>
                </ul>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <table class="table table-striped table-bordered table-hover dataTables-example" id="test">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Terminal Serial</th>
                        <th>Site Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                        @for (var i = 0; i < Model.serialnumber.Count; i++)
                        {
                    <tr>                      
                        <td>@Html.DisplayFor(x => Model.is_attached[i])</td>
                        <td>@Html.DisplayFor(x => Model.serialnumber[i])</td>
                        <td>@Html.DisplayFor(x => Model.site[i])</td>
                        <td class="text-right">
                            <div class="btn-group">
                                @if (Model.is_attached[i] == "Attached")
                                {
                                    <button class="btn-white btn btn-xs">Cannot Edit While Attached to Site, Please Detach from site first</button>
                                }
                                else
                                {
                                    <button class="btn-white btn btn-xs">@Html.ActionLink("Edit", "edit_page", new { id = Html.ValueFor(x => Model.site_id[i]) })</button>
                                }
                            </div>
                        </td>
                    </tr>
                        }
                </tbody>
            </table>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('.dataTables-example').DataTable({
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy' },
                { extend: 'csv' },
                { extend: 'excel', title: 'ExampleFile' },
                { extend: 'pdf', title: 'ExampleFile' },

                {
                    extend: 'print',
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            "bDestroy": true

        });
    });

</script>


<script>

    $(function myFunction() {

        $("#serialspinner").remove();

    });




</script>

Inspinia_MVC5/Views/siteaccount/site.cshtml
@model newtest.Models.sitelistmodel.sitemodellist

<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Site List</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-wrench"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="#">Config option 1</a>
                    </li>
                    <li>
                        <a href="#">Config option 2</a>
                    </li>
                </ul>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <table class="table table-striped table-bordered table-hover dataTables-example" id="testing">
              
                 <thead>
                    <tr>
                        <th>Status</th>
                        <th>Last Seen</th>
                        <th>Site Name</th>
                        <th>Terminal Serial</th>
                        <th>Time Zone</th>
                        <th>HG Status</th>
                        <th>IO Alarm</th>
                        <th>Data Types</th>
                        <th>Action</th>
                    </tr>
                </thead>
             
                <tbody>
                    @for (var i = 0; i < Model.sites.Count; i++)
                    {
                    <tr>
                        <td>@Html.DisplayFor(x => Model.status[i])</td>
                        <td>@Html.DisplayFor(x => Model.date_lastseen[i])</td>
                        <td>@Html.DisplayFor(x => Model.sites[i])</td>
                        <td>@Html.DisplayFor(x => Model.serialnumber[i])</td>
                        <td>@Html.DisplayFor(x => Model.timezone[i])</td>
                        <td>@Html.DisplayFor(x => Model.hgstatus_count[i])</td>
                        <td>@Html.DisplayFor(x => Model.ioalarms_count[i])</td>
                        <td>@Html.DisplayFor(x => Model.graph_data_count[i])</td>

                        <td class="text-right">
                            <div class="btn-group">
                                <button class="btn-white btn btn-xs">@Html.ActionLink("Edit", "delete_page", new { site = "wtf" })</button>
                                <button class="btn-white btn btn-xs">@Html.ActionLink("Edit", "edit_page", new { site = "wtf" })</button>
                            </div>
                        </td>
                       
                    </tr>
                    }
                </tbody>
          
            </table>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('.dataTables-example').DataTable({
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy' },
                { extend: 'csv' },
                { extend: 'excel', title: 'ExampleFile' },
                { extend: 'pdf', title: 'ExampleFile' },

                {
                    extend: 'print',
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            "bDestroy": true
        });
    });

</script>

<script>

    $(function myFunction() {

        $("#sitespinner").remove();

    });




</script>