Inspinia_MVC5/Controllers/customurlController.cs
using stay_calm_db_tests;
using ee.Models.chparamModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Inspinia_MVC5.Controllers
{
    public class customurlController : Controller
    {
        public async Task<ActionResult> chparams(String serialsite, String xpa, String ypa, String zpa, String apa)
        {

            if (serialsite == null)
            {
                serialsite = "0890CA";
            }
            else
            {
                serialsite = serialsite.Replace(" ", string.Empty);

            }
            userContext db = new userContext();
            if (xpa != null)
            {
               
                var ch_response = db.chparamdbs.Where(x => x.sitetoboards.serialboard == serialsite).FirstOrDefault();

                double x_int = 10;
                double.TryParse(xpa, out x_int);

                double y_int = 10;
                double.TryParse(ypa, out y_int);

                double z_int = 10;
                double.TryParse(zpa, out z_int);

                double a_int = 10;
                double.TryParse(apa, out a_int);


                if (ch_response != null)
                {
                    ch_response.xparams = x_int;
                    ch_response.yparams = y_int;

                    ch_response.zparams = z_int;
                    ch_response.aparams = a_int;

                    db.Entry(ch_response).State = EntityState.Modified;
                    await db.SaveChangesAsync();

                }
            }

            chparamdb adding_sites = new chparamdb();
            adding_sites.serial_site = new List<String>();

            int count = 0;
            var site_to_comms = await (from y in db.chparamdbs
                                       select y.sitetoboards).ToListAsync();

            foreach (var item in site_to_comms)
            {
                adding_sites.serial_site.Add(item.serialboard);

                if (item.serialboard.Contains(serialsite))
                {
                    ViewBag.site_selected = count;
                }
                else
                { count = count + 1; }
            }


            var x_display = await (from x in db.chparamdbs
                                   where x.sitetoboards.serialboard == serialsite
                                   select new {
                                          x.xparams,
                                          x.yparams,
                                          x.zparams,
                                          x.aparams
                                         }).FirstOrDefaultAsync();
            

            ViewBag.x_pa = x_display.xparams.ToString();
            ViewBag.y_pa = x_display.yparams.ToString();


            ViewBag.z_pa = x_display.zparams.ToString();
            ViewBag.a_pa = x_display.aparams.ToString();




            return View(adding_sites);
        }



    }
}

Inspinia_MVC5/Controllers/ioalarmsController.cs
using newtest.Models.ioalarmmodel;
using stay_calm_db_tests;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspinia_MVC5.Controllers
{
    public class ioalarmsController : Controller
    {
        private userContext db = new userContext();

        public ActionResult ioalarm_history(string site)
        {
                  ioalarm_visualdisplay ioalarmVisualdisplay = new ioalarm_visualdisplay();
                  ioalarmVisualdisplay.alarm_names = new List<string>();
                  ioalarmVisualdisplay.site_all = new List<string>();
                  ioalarmVisualdisplay.site_id = new List<string>();
                  ioalarmVisualdisplay.alarm_ids = new List<string>();

                    var all_sites = (from a in db.siteuser
                                     select new
                                     {
                                         a.user_site,
                                         a.Id
                                     }).ToList();

                    if (site == null)
                    {
                       site = all_sites.Select(x => x.Id).FirstOrDefault().ToString();
                    }

                     int count = 0;

                    foreach (var item in all_sites)
                    {

                        ioalarmVisualdisplay.site_all.Add(item.user_site);
                        ioalarmVisualdisplay.site_id.Add(item.Id.ToString());


                        if (site == item.Id.ToString())
                        {
                            ViewBag.site_selected = count;
                        }
                        else
                        { count = count + 1; }


                    }

                 var alarm_list = db.io_alarms.Where(y => y.siteuser.Id.ToString() == site).ToList();
                  
                  
                  if (alarm_list.Count() == 0)
                  {
                    ioalarmVisualdisplay.alarm_names.Add("This site contains no Alarms");
                    ioalarmVisualdisplay.alarm_ids.Add("null");
                  }
                  else
                  {
                    foreach (var items in alarm_list)
                    {
                      ioalarmVisualdisplay.alarm_names.Add(items.alarm_name);
                      string str = items.switch_number.ToString();
                      ioalarmVisualdisplay.alarm_ids.Add(str);
                    }
                  }

                String today = DateTime.UtcNow.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                String yesterday = DateTime.UtcNow.AddDays(-1.0).ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);




                ViewBag.yesterday = yesterday;
                ViewBag.today = today;

               return View(ioalarmVisualdisplay);
          }


        public PartialViewResult ioalarm_data(string[] options, string sitename, string select_from, string to_select)
        {
            ioalarm_selection ioalarmSelection = new ioalarm_selection();
            ioalarmSelection.selected_num = new List<string>();
            ioalarmSelection.selected_name = new List<string>();
            ioalarmSelection.selected_for_id = new List<string>();
            ioalarmSelection.sitename = new List<string>();
            ioalarmSelection.data_from = new List<string>();
            ioalarmSelection.data_to = new List<string>();

            int site_int;
            int.TryParse(sitename, out site_int);

            ioalarmSelection.sitename.Add(sitename);
            ioalarmSelection.data_from.Add(select_from);
            ioalarmSelection.data_to.Add(to_select);

            var list = db.io_alarms.Where(x => x.siteuser.Id == site_int).Select(x => new
            {
                switch_number = x.switch_number,
                alarm_name = x.alarm_name
            }).ToList();

            for (int index = 0; index < options.Length; ++index)
            {
                ioalarmSelection.selected_num.Add(options[index]);
                ioalarmSelection.selected_for_id.Add("alarm" + options[index]);

                foreach (var data in list)
                {
                    if (data.switch_number.ToString() == options[index])
                        ioalarmSelection.selected_name.Add(data.alarm_name);
                }
            }
            return PartialView(ioalarmSelection);
        }


        // loadingids = Alarm + option[index]  e.g. alarm1
        // alarm_name =  alarm name  e.g. sw1
        // Sitename = Site name 
        // options = number = sw1 = 1 

        public PartialViewResult ioalarm_plot(string options, string from, string to, string sitename, string loadingids, string alarm_name)
        {
            ioalarm_plotmodel ioalarmPlotmodel = new ioalarm_plotmodel();
            ioalarmPlotmodel.selected_num = new List<string>();
            ioalarmPlotmodel.year_graph = new List<long>();
            ioalarmPlotmodel.year_last_date = new List<string>();
            ioalarmPlotmodel.value_of_graph = new List<double>();

            ioalarmPlotmodel.graph_min = new List<string>();
            ioalarmPlotmodel.graph_max = new List<string>();
            ioalarmPlotmodel.graph_avg = new List<string>();

            ioalarmPlotmodel.graph_data_date = new List<string>();
            ioalarmPlotmodel.graph_data_late = new List<string>();
            ioalarmPlotmodel.alarm_graph_store = new List<string>();
            ioalarmPlotmodel.sitename = new List<string>();
            ioalarmPlotmodel.data_from = new List<string>();
            ioalarmPlotmodel.data_to = new List<string>();

            alarm_name = alarm_name.Replace(" ", "_");

            ViewBag.title = alarm_name;

            ViewBag.name = "ele" + options;

            ioalarmPlotmodel.selected_num.Add(options);

            int switch_number = 0;
            int.TryParse(options, out switch_number);

            DateTime date_from = DateTime.Parse(from).AddHours(-11);
            DateTime date_to = DateTime.Parse(to).AddDays(1);

           
            String  Gmt_convert = "AUS Eastern Standard Time";

            ViewBag.timezone = Gmt_convert;
            ViewBag.datefrom = date_from;
            ViewBag.dateto = date_to;


            string binary = "";
            string bin_string = "";
            int binary_form = 0;
            int binary_value = 0;

            /* var get_data_points = (from x in db.io_alarms_value
                                    where x.siteuser.user_site == sitename && (x.date >= date_from && x.date <= date_to)
                                    select x).ToList();
            */
            int site_int;
            int.TryParse(sitename, out site_int);

            var get_data_points = (from x in db.io_alarms_value
                                   where x.siteuser.Id == site_int
                                   select x).ToList();



            var sorting_dates = get_data_points.OrderBy(s => s.date);

            var final_data = sorting_dates.Where(x => x.date >= date_from && x.date <= date_to).ToList();
            


            if (final_data.Count() == 0)
            {
                return PartialView();
            }
            else { 

                    foreach (var item in final_data)
                   {

                    var est = TimeZoneInfo.FindSystemTimeZoneById(Gmt_convert);
                    var targetTime = TimeZoneInfo.ConvertTime(item.date, est);

                    ioalarmPlotmodel.alarm_graph_store.Add(targetTime.ToString());

                    // If there is a comma 
                    string first_bin;
                    string second_bin;

                    if (item.value.Contains(','))
                    {
                        string[] brk = item.value.Split(',');
                        first_bin = brk[0];
                        second_bin = brk[1];
                    }
                    else
                    {
                        first_bin = item.value;
                        second_bin = "0";
                    }

                    // if first alarm = 1, then 8-1 = 7 
                    // if eight alarm = 8, then 8-8 = 0

                    if (switch_number > 8)
                    {
                        int.TryParse(second_bin, out binary_form);
                        binary = Convert.ToString(binary_form, 2).PadLeft(8, '0');
                        bin_string = binary[16 - switch_number].ToString();

                        int.TryParse(bin_string, out binary_value);
                        ioalarmPlotmodel.value_of_graph.Add(binary_value);
                    }
                    else
                    {
                        int.TryParse(first_bin, out binary_form);
                        binary = Convert.ToString(binary_form, 2).PadLeft(8, '0');
                        bin_string = binary[8 - switch_number].ToString();

                        int.TryParse(bin_string, out binary_value);
                        ioalarmPlotmodel.value_of_graph.Add(binary_value);
                    }




                    var time_convert_y = targetTime.ToString("yyyy");
                    int year = Convert.ToInt32(time_convert_y);

                    var time_convert_m = targetTime.ToString("MM");
                    int month = Convert.ToInt32(time_convert_m);

                    var time_convert_d = targetTime.ToString("dd");
                    int day = Convert.ToInt32(time_convert_d);

                    var time_convert_h = targetTime.ToString("HH");
                    int hour = Convert.ToInt32(time_convert_h);

                    var time_convert_min = targetTime.ToString("mm");
                    int min = Convert.ToInt32(time_convert_min);

                    var time_convert_sec = targetTime.ToString("ss");
                    int sec = Convert.ToInt32(time_convert_sec);

Inspinia_MVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Elemental Elec | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'16fadfcd-7dff-4b6e-8b0e-16da245064a6'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>



    <!-- Skin configuration box -->
    <!-- @Html.Partial("_SkinConfig") -->

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
          <!-- Html.Partial("_Footer")-->

        </div>
        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Inspinia_MVC5/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>INSPINIA | @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")

    <!--Uses CSS to get the spinner-->
    <link rel="stylesheet" href="~/Content/splash/css/main.css">

    <!--This controls the spinner-->
    <script src="~/Content/splash/js/vendor/modernizr-2.6.2.min.js"></script>


</head>

<body>
 
        <!--Loader is the spinning animation-->


            <!-- Skin configuration box -->
            <!-- @Html.Partial("_SkinConfig") -->
            <!-- Wrapper-->
            <!-- PageClass give you ability to specify custom style for specific view based on action -->
            <div id="wrapper" class="@Html.PageClass()">

                <!-- Navigation -->
                @Html.Partial("_Navigation")

                <!-- Page wraper -->
                <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

                    <!-- Top Navbar -->
                    @Html.Partial("_TopNavbar")

                    <!-- Main view  -->
                    @RenderBody()

                    <!-- Footer -->
                    <!-- Html.Partial("_Footer")-->

                </div>

                <!-- End page wrapper-->
                <!-- Right Sidebar -->
                @Html.Partial("_RightSidebar")

            </div>

   
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)

    <!-- This controls the transition -->
    <script src="~/Content/splash/js/main.js"></script>
</body>
</html>


<!--
    
    <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
-->

Inspinia_MVC5/Views/Shared/_Layout_3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Elemental Elec | @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/css")
</head>
<body class="fixed-sidebar no-skin-config full-height-layout">

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper" class="@Html.PageClass()">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()


        </div>
        <!-- End page wrapper-->
        <!-- Right Sidebar -->
        @Html.Partial("_RightSidebar")

    </div>
    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Inspinia_MVC5/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="~/images/eelogo.png" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Jacob EE</strong>
                            </span> <span class="text-muted text-xs block">Software Engineer<b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="@Url.Action("profile_view", "Profile")">Profile</a></li>
                        <li><a href="@Url.Action("profile_sites", "Profile")">Sites</a></li>
                        <li><a href="@Url.Action("profile_tasks", "Profile")">Tasks</a></li>
                        <li class="divider"></li>   
                        <li><a href="@Url.Action("Index","Home")">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    EE
                </div>
            </li>

            <!-- Dashboard -->
            <li class="@Html.IsSelected(controller: "Dashboards")">
                <a href="@Url.Action("Dashboard", "Dashboard")"><i class="fa fa-th-large"></i> <span class="nav-label" data-i18n="nav.dashboard">Dashboards</span></a>
            </li>
          
            <!-- Site Test History -->
            <li class="@Html.IsSelected(controller: "Graphs")">
                <a href="@Url.Action("site_data_test", "HistorySite")"><i class="fa fa-bar-chart-o"></i> <span class="nav-label" data-i18n="nav.graphs">Site Test History</span></a>
            </li>

            <!-- I/O Alarms -->
            <li class="@Html.IsSelected(controller: "Metrics")">
                <a href="@Url.Action("ioalarm_history", "ioalarms")"><i class="fa fa-pie-chart"></i> <span class="nav-label" data-i18n="nav.metrics">I/O Alarms</span> </a>
            </li>
           
            <!-- Account Settings -->
            <li class="@Html.IsSelected(controller: "Forms")">
                <a href="@Url.Action("site_list","siteaccount")"><i class="fa fa-edit"></i> <span class="nav-label" data-i18n="nav.forms">Account Settings</span></a>
            </li>
              
            <!-- Site Settings -->
            @*<li class="@Html.IsSelected(controller: "Pages")">
                <a href="#"><i class="fa fa-files-o"></i> <span class="nav-label" data-i18n="nav.otherpages">Site Settings</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse @Html.IsSelected(controller: "Pages", cssClass: "in")">
                    <li class="@Html.IsSelected(action: "SearchResults")"><a href="@Url.Action("SearchResults", "Pages")">Normal User Accounts</a></li>
                    <li class="@Html.IsSelected(action: "LockScreen")"><a href="@Url.Action("LockScreen", "Pages")">Site Accounts</a></li>
                    <li class="@Html.IsSelected(action: "Invoice")"><a href="@Url.Action("Invoice", "Pages")">Serial Accounts</a></li>
                </ul>
            </li>*@

            <!-- Comms Responses -->
            <li class="@Html.IsSelected(controller: "Miscellaneous")">
                <a href="@Url.Action("comms_response","response")"><i class="fa fa-files-o"></i> <span class="nav-label" data-i18n="nav.miscellaneous">Comms Response</span></a>
            </li>

            <!-- Alert Configuration -->
            <li class="@Html.IsSelected(controller: "UIElements")">
                <a href="@Url.Action("emailsms","emailandsms")"><i class="fa fa-globe"></i><span class="nav-label" data-i18n="nav.uielements">Email/SMS Configuration</span></a>
            </li>


            <!-- chparams -->
            <li class="@Html.IsSelected(controller: "CH_Elements")">
                <a href="@Url.Action("chparams","customurl")"><i class="fa fa-globe"></i><span class="nav-label" data-i18n="nav.uielements">CH Params</span></a>
            </li>
      
            @*<li>
                <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label" data-i18n="nav.menulevels">Management System </span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>

                        </ul>
                    </li>
                    <li><a href="#">Second Level Item</a></li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                </ul>
            </li>*@

            @*<li class="@Html.IsSelected(controller: "CSSAnimations")">
                <a href="@Url.Action("Index", "CSSAnimations")"><i class="fa fa-magic"></i> <span class="nav-label" data-i18n="nav.animations">CSS Animations </span><span class="label label-info pull-right">62</span></a>
            </li>
            <li class="special_link @Html.IsSelected(controller: " Landing")">
                <a href="@Url.Action("Index", "Landing")"><i class="fa fa-star"></i> <span class="nav-label" data-i18n="nav.landing">Landing page</span></a>
            </li>
            <li class="special_link @Html.IsSelected(controller: " Scaffolding")">
                <a href="@Url.Action("Index", "Scaffolding")"><i class="fa fa-database"></i> <span class="nav-label">Scaffolding Example</span></a>
            </li>
            <li class="special_link @Html.IsSelected(controller: " Json")">
                <a href="@Url.Action("Index", "Json")"><i class="fa fa-plug"></i> <span class="nav-label">JSON Examples</span></a>
            </li>*@

         
        </ul>
    </div>
</nav>